"""adiciona tabela encaminhamentos

Revision ID: 1849d3093717
Revises: 45e7a1bd93b0
Create Date: 2026-07-24 16:56:55.201069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1849d3093717'
down_revision: Union[str, Sequence[str], None] = '45e7a1bd93b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encaminhamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('especialidade_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.ForeignKeyConstraint(['especialidade_id'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encaminhamentos_id'), 'encaminhamentos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encaminhamentos_id'), table_name='encaminhamentos')
    op.drop_table('encaminhamentos')
    # ### end Alembic commands ###
