"""adiciona campo versao em cids

Revision ID: 1fb83e3aa3f6
Revises: 4faf3626c6b9
Create Date: 2026-07-26 18:12:11.715272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb83e3aa3f6'
down_revision: Union[str, Sequence[str], None] = '4faf3626c6b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cids', sa.Column('versao', sa.String(), server_default='CID-10', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cids', 'versao')
    # ### end Alembic commands ###
