"""adiciona campo ativo em pacientes (soft delete)

Revision ID: 24d356e03b5c
Revises: 54e372437a1b
Create Date: 2026-07-25 14:18:08.397821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24d356e03b5c'
down_revision: Union[str, Sequence[str], None] = '54e372437a1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pacientes', sa.Column('ativo', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pacientes', 'ativo')
    # ### end Alembic commands ###
