"""adiciona tabela anexos

Revision ID: 4faf3626c6b9
Revises: dbc3562fe253
Create Date: 2026-07-26 16:48:06.968152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4faf3626c6b9'
down_revision: Union[str, Sequence[str], None] = 'dbc3562fe253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anexos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('exame_id', sa.Integer(), nullable=True),
    sa.Column('profissional_id', sa.Integer(), nullable=True),
    sa.Column('nome_original', sa.String(), nullable=False),
    sa.Column('nome_armazenado', sa.String(), nullable=False),
    sa.Column('tipo_conteudo', sa.String(), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['exame_id'], ['exames.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anexos_id'), 'anexos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_anexos_id'), table_name='anexos')
    op.drop_table('anexos')
    # ### end Alembic commands ###
