"""adiciona cid_sugerido e ordem em hipoteses_diagnosticas

Revision ID: d5537d75f316
Revises: fc01370b6810
Create Date: 2026-07-26 19:04:01.733652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5537d75f316'
down_revision: Union[str, Sequence[str], None] = 'fc01370b6810'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hipoteses_diagnosticas', sa.Column('cid_sugerido', sa.String(), nullable=True))
    op.add_column('hipoteses_diagnosticas', sa.Column('ordem', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hipoteses_diagnosticas', 'ordem')
    op.drop_column('hipoteses_diagnosticas', 'cid_sugerido')
    # ### end Alembic commands ###
