"""adiciona modulos, perfis de acesso e vinculo com profissional

Revision ID: dbc3562fe253
Revises: 24d356e03b5c
Create Date: 2026-07-25 20:43:12.964303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbc3562fe253'
down_revision: Union[str, Sequence[str], None] = '24d356e03b5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_index(op.f('ix_modulos_id'), 'modulos', ['id'], unique=False)
    op.create_table('perfis_acesso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_index(op.f('ix_perfis_acesso_id'), 'perfis_acesso', ['id'], unique=False)
    op.create_table('perfil_acesso_modulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_acesso_id', sa.Integer(), nullable=False),
    sa.Column('modulo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['modulo_id'], ['modulos.id'], ),
    sa.ForeignKeyConstraint(['perfil_acesso_id'], ['perfis_acesso.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_perfil_acesso_modulos_id'), 'perfil_acesso_modulos', ['id'], unique=False)
    # SQLite não suporta ALTER TABLE ADD CONSTRAINT diretamente - precisa
    # do modo batch (recria a tabela por baixo dos panos, copiando os
    # dados). op.add_column + op.create_foreign_key soltos (como o
    # autogenerate gerou originalmente) falham com
    # "No support for ALTER of constraints in SQLite dialect".
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil_acesso_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_profissionais_perfil_acesso_id', 'perfis_acesso', ['perfil_acesso_id'], ['id']
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profissionais', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profissionais_perfil_acesso_id', type_='foreignkey')
        batch_op.drop_column('perfil_acesso_id')
    op.drop_index(op.f('ix_perfil_acesso_modulos_id'), table_name='perfil_acesso_modulos')
    op.drop_table('perfil_acesso_modulos')
    op.drop_index(op.f('ix_perfis_acesso_id'), table_name='perfis_acesso')
    op.drop_table('perfis_acesso')
    op.drop_index(op.f('ix_modulos_id'), table_name='modulos')
    op.drop_table('modulos')
    # ### end Alembic commands ###
