"""adiciona tabelas hipoteses_diagnosticas e fontes_hipoteses

Revision ID: fc01370b6810
Revises: 1fb83e3aa3f6
Create Date: 2026-07-26 18:42:31.898106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc01370b6810'
down_revision: Union[str, Sequence[str], None] = '1fb83e3aa3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hipoteses_diagnosticas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consulta_id', sa.Integer(), nullable=False),
    sa.Column('condicao', sa.String(), nullable=False),
    sa.Column('justificativa', sa.Text(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['consulta_id'], ['consultas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hipoteses_diagnosticas_id'), 'hipoteses_diagnosticas', ['id'], unique=False)
    op.create_table('fontes_hipoteses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hipotese_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['hipotese_id'], ['hipoteses_diagnosticas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fontes_hipoteses_id'), 'fontes_hipoteses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fontes_hipoteses_id'), table_name='fontes_hipoteses')
    op.drop_table('fontes_hipoteses')
    op.drop_index(op.f('ix_hipoteses_diagnosticas_id'), table_name='hipoteses_diagnosticas')
    op.drop_table('hipoteses_diagnosticas')
    # ### end Alembic commands ###
